# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4245d434c658ec9b88d4c4172f5620ff33ef2c9f1729dae4e43a4264a947ec0ccd0363054e7fee478be6a821ae17c5426b5e895d0709d4a09d648f6602ab7b75

test:
  secret_key_base: e6ac311f206c508d16a4c970e4128d542407e6cd5098683b1db8d15525186fb80e61de86ef220be5309b239bd019fcf84ec40e8fb49084642c105754b31be4dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
